version: '3'
services:
  postgres:
    container_name: app_pg
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
    ports:
      [5432:5432]
  redis:
    container_name: app_redis
    image: redis:6.2.1
    ports:
      [6379:6379]
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - AWS_DEFAULT_OUTPUT=json
      - DEBUG=1
    volumes:
      - ./tmp/localstack/data:/tmp/localstack/data
      - ./.aws:/etc/localstack/init/ready.d